Repository MTES-MCT/monitorfish, pull requests merged in 2024-12, with the labels that each got.

#3938 Montée de version geopandas
  datascience/poetry.lock
  datascience/pyproject.toml
Labels: dependencies

#3952 Réduction du rayon de `buffer` dans l'attribution de zones FAO aux ports
  datascience/src/pipeline/flows/ports.py
Labels: bug, data

#3953 Tech - Amélioration des performances des requêtes `logbook`
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
Labels: tech. enhancement

#3954 Tech - Correction de la page de login
  frontend/src/auth/components/Login.tsx
Labels: tech. enhancement

#3842 Tech - Ajout d'un script de génération de données factices PNOs
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/generate_perf_data.js
Labels: bug

#3971 Résolution du problème des alertes qui remontent malgré la présence d'une suspension d'alerte
  datascience/config.py
  datascience/src/pipeline/flows/missing_dep_alerts.py
  datascience/src/pipeline/flows/missing_far_alerts.py
  datascience/src/pipeline/flows/position_alerts.py
  datascience/src/pipeline/flows/suspicions_of_under_declaration_alerts.py
  datascience/src/pipeline/queries/monitorfish/missing_deps.sql
  datascience/src/pipeline/queries/monitorfish/silenced_alerts.sql
  datascience/src/pipeline/queries/monitorfish/suspicions_of_under_declaration.sql
  datascience/src/pipeline/shared_tasks/alerts.py
  datascience/tests/test_data/remote_database/V666.19__Reset_test_silenced_alerts.sql
  datascience/tests/test_pipeline/test_flows/test_missing_dep_alerts.py
  datascience/tests/test_pipeline/test_flows/test_missing_far_alerts.py
  datascience/tests/test_pipeline/test_flows/test_position_alerts.py
  datascience/tests/test_pipeline/test_flows/test_suspicions_of_under_declaration_alerts.py
  datascience/tests/test_pipeline/test_shared_tasks/test_alerts.py
Labels: bug, data

#3987 Montée de version h3
  datascience/poetry.lock
  datascience/pyproject.toml
  datascience/src/pipeline/flows/anchorages.py
  datascience/src/pipeline/helpers/spatial.py
  datascience/tests/test_pipeline/test_flows/test_regulations_checkup.py
Labels: dependencies
