Repository MTES-MCT/monitorfish, pull requests merged in 2024-08, with the labels that each got.

#3394 Contrôle - Ajout de champs `actionEndDateTime` et `observationsByUnit`
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/Patchable.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/MissionAction.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/PatchableMissionAction.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/mappers/PatchEntity.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/PatchMissionAction.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/MissionActionDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicMissionActionsController.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/input/PatchableMissionActionDataInput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/MissionActionEntity.kt
  backend/src/main/resources/db/migration/internal/V0.268__Update_action_table.sql
  backend/src/main/resources/db/migration/internal/V0.269__Update_action_table.sql
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/PatchMissionActionUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/TestUtils.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicMissionActionsControllerITests.kt
  datascience/tests/test_pipeline/test_flows/test_controls.py
Labels: feat. enhancement

#3498 Préavis – Problème de préavis qui se ferme sans pop-up de confirmation
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/error_handling.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/error_handling.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/utils.ts
  frontend/src/components/SideWindowCard.tsx
  frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Form.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Form.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Header.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/index.tsx
  frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx
  frontend/src/features/PriorNotification/slice.ts
  frontend/src/hooks/useFormikDirtyOnceEffect.tsx
Labels: bug

#3500 Préavis – Tracer la durée des appels API en Frontend via Sentry
  frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts
  frontend/cypress/e2e/utils/getUtcizedDayjs.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/api.ts
  frontend/src/index.tsx
Labels: tech. enhancement

#3525 Préavis - Amélioration de la vitesse de la liste des PNOs
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/Utils.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/VesselRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetNumberToVerify.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/utils/PaginatedList.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LogbookReportEntity.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBVesselRepository.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetNumberToVerifyUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepositoryITests.kt
Labels: feat. enhancement

#3529 [Tech] Corrige les utilitaires des tests E2E Puppeteer
  frontend/puppeteer/e2e/missions.spec.ts
  frontend/puppeteer/e2e/utils.ts
  frontend/puppeteer/setup.ts
Labels: bug, tech. enhancement

#3534 Préavis – Restaure la réinitialisation de l'état d'envoi durant la sauvegarde auto des préavis JPE
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt
Labels: bug

#3533 Préavis - Les lignes de détail des préavis doivent se refermer en cas de tri ou de filtrage du tableau
  frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx
Labels: bug

#3547 Simplification de la logique de récupération des PNOs logbook
  Makefile
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookMessage.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/LogbookReportRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/PriorNotificationDetailDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/PriorNotificationListItemDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LogbookReportEntity.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
  backend/src/main/resources/db/testdata/V666.2.1__Insert_more_dummy_vessels.sql
  backend/src/main/resources/db/testdata/V666.5.1__Insert_more_pno_logbook_reports.sql
  backend/src/main/resources/db/testdata/json/V666.2.1__Insert_more_dummy_vessels.jsonc
  backend/src/main/resources/db/testdata/json/V666.5.1__Insert_more_pno_logbook_reports.jsonc
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookMessageUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationsUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotificationUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/error_handling.spec.ts
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts
  frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts
  frontend/cypress/e2e/side_window/prior_notification_card/error_handling.spec.ts
  frontend/package.json
  frontend/src/api/BackendApi.types.ts
  frontend/src/features/PriorNotification/PriorNotification.types.ts
  frontend/src/features/PriorNotification/components/PriorNotificationList/Row.tsx
  frontend/src/features/PriorNotification/components/PriorNotificationList/cells/ActionButtonsCell.tsx
  frontend/src/features/PriorNotification/components/PriorNotificationList/columns.tsx
  frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx
  frontend/src/features/PriorNotification/utils.ts
Labels: bug

#3548 Ajout d'une colonne `activity_datetime_utc` dans la table logbook reports
  backend/src/main/resources/db/migration/internal/V0.273__Update_logbook_reports_table.sql
  datascience/src/pipeline/parsers/ers/log_parsers.py
  datascience/src/pipeline/parsers/flux/flux.py
  datascience/src/pipeline/parsers/utils.py
  datascience/tests/test_pipeline/test_flows/test_logbook.py
  datascience/tests/test_pipeline/test_parsers/test_ers.py
  datascience/tests/test_pipeline/test_parsers/test_flux.py
  datascience/tests/test_pipeline/test_parsers/test_utils.py
Labels: feat. enhancement

#3552 Tech - Ajoute quelques commandes au Makefile
  Makefile
  backend/scripts/test-watch.sh
  datascience/docs/source/contributing.rst
Labels: tech. enhancement

#3541 Préavis - Trier les zones FAO par ordre décroissant de fréquence d'usage dans le formulaire
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/fao_area/FaoArea.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlan.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/FAOAreasRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/FaoAreaRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeFaoAreasFromCoordinates.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeVesselFaoAreas.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/GetFaoAreas.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegments.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/Utils.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FaoAreaController.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/FaoAreaEntity.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFAOAreasRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFaoAreaRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBFAOAreasRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBFaoAreaRepository.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeFaoAreasFromCoordinatesUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeVesselFaoAreasUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/GetFaoAreasUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/UtilsUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FaoAreaControllerITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFaoAreaRepositoryITests.kt
  frontend/src/hooks/useGetFaoAreasAsOptions.ts
Labels: feat. enhancement

#3559 Préavis - Supprime le second tri superflu des zones FAO
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/GetFaoAreas.kt
Labels: bug

#3530 Préavis – Écrire des tests d'intégration couvrant l'ensemble des status et actions possibles
  backend/scripts/test-watch.sh
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/ManualPriorNotificationRepository.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepository.kt
  backend/src/main/resources/db/testdata/V666.2.1__Insert_more_dummy_vessels.sql
  backend/src/main/resources/db/testdata/V666.28__Insert_dummy_prior_notification_pdf_documents.sql
  backend/src/main/resources/db/testdata/V666.5.1__Insert_more_pno_logbook_reports.sql
  backend/src/main/resources/db/testdata/json/V666.2.1__Insert_more_dummy_vessels.jsonc
  backend/src/main/resources/db/testdata/json/V666.5.1__Insert_more_pno_logbook_reports.jsonc
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdateLogbookPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/AbstractDBTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepositoryITests.kt
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/behavior.spec.ts
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts
Labels: bug, tech. enhancement

#3558 Préavis - Protéger l'URL de téléchargement des préavis avec Cerbère
  Makefile
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationController.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationControllerITests.kt
  frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts
  frontend/cypress/e2e/side_window/mission_list/export_activity_reports.spec.ts
  frontend/cypress/e2e/side_window/reporting_list/actions.spec.ts
  frontend/cypress/e2e/vessels/vessels_list.spec.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/commands/cleanDownloadedFiles.ts
  frontend/cypress/support/commands/getDownloadedFileContent.ts
  frontend/cypress/support/e2e.ts
  frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx
  frontend/src/features/PriorNotification/priorNotificationApi.ts
  frontend/src/utils/downloadAsPdf.ts
Labels: tech. enhancement

#3574 Résolution du bug de diffusion des préavis quand un numéro de téléphone ou un email est un string vide
  datascience/src/pipeline/shared_tasks/control_units.py
  datascience/tests/test_pipeline/conftest.py
Labels: bug

#3570 Préavis – Permettre d'entrer une zone par espèce capturée dans le formulaire
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/PatchableMissionAction.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeManualPriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationComputeDataInput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationFishingCatchDataInput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationFormDataInput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ManualPriorNotificationFishingCatchDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ManualPriorNotificationFormDataOutput.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdateLogbookPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotificationITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt
  frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts
  frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts
  frontend/src/features/PriorNotification/PriorNotification.types.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Form.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/constants.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFaoAreaSelect/constants.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFaoAreaSelect/index.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/styles.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/utils.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/index.tsx
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/types.ts
  frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/utils.tsx
  frontend/src/features/PriorNotification/useCases/openManualPriorNotificationForm.ts
Labels: feat. enhancement
