Repository MTES-MCT/monitorfish, pull requests merged in 2025-05, with the labels that each got.

#4270 Correction d'un bug dans l'enrichissement des préavis
  datascience/src/pipeline/flows/enrich_logbook.py
  datascience/src/pipeline/queries/monitorfish/pno_catches.sql
  datascience/tests/test_pipeline/test_flows/test_enrich_logbook.py
Labels: bug

#4267 [Mission] Trier les options des menus déroulants "Espèces" et "Engins"
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/gear/GetAllGears.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/species/GetAllSpeciesAndSpeciesGroups.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/gear/GetAllGearsUTests.kt
  frontend/cypress/e2e/sidebars/regulatory_layers.spec.ts
Labels: feat. enhancement

#4286 Prise en compte des profils de navires dans la note de risque
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/risk_factor/VesselRiskFactor.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselController.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActiveVesselDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/DynamicVesselGroupWithVesselsDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/FixedVesselGroupWithVesselsDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/RiskFactorDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/SelectedVesselDataOutput.kt
  backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/RiskFactorEntity.kt
  backend/src/main/resources/db/migration/internal/V0.301__Update_current_segments_table.sql
  backend/src/main/resources/db/migration/internal/V0.302__Update_risk_factors_table.sql
  backend/src/main/resources/db/migration/internal/V0.303__Update_vessel_profiles_table.sql
  backend/src/main/resources/db/testdata/V666.11__Insert_dummy_risk_factors.sql
  backend/src/main/resources/db/testdata/json/V666.11__Insert_dummy_risk_factors.jsonc
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/vessel_group/DynamicVesselGroupUTests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt
  backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/RiskFactorDataOutputUTests.kt
  datascience/config.py
  datascience/src/pipeline/entities/vessel_profiles.py
  datascience/src/pipeline/flows/current_segments.py
  datascience/src/pipeline/flows/risk_factor.py
  datascience/src/pipeline/flows/vessel_profiles.py
  datascience/src/pipeline/queries/data_warehouse/gear_onboard.sql
  datascience/src/pipeline/queries/data_warehouse/port_profiles.sql
  datascience/src/pipeline/queries/data_warehouse/profiles.sql
  datascience/src/pipeline/queries/monitorfish/ports_facade.sql
  datascience/src/pipeline/queries/monitorfish/recent_segments.sql
  datascience/src/pipeline/queries/monitorfish/usual_segments.sql
  datascience/src/pipeline/shared_tasks/segments.py
  datascience/tests/test_data/remote_database/V666.11__Reset_test_risk_factors.sql
  datascience/tests/test_data/remote_database/V666.15__Reset_test_current_segments.sql
  datascience/tests/test_data/remote_database/V666.43__Reset_test_vessel_profiles.sql
  datascience/tests/test_pipeline/test_flows/conftest.py
  datascience/tests/test_pipeline/test_flows/test_current_segments.py
  datascience/tests/test_pipeline/test_flows/test_risk_factor.py
  datascience/tests/test_pipeline/test_flows/test_vessel_profiles.py
  datascience/tests/test_pipeline/test_shared_tasks/test_segments.py
  frontend/cypress/e2e/main_window/vessel_sidebar/resume.spec.ts
  frontend/src/features/FleetSegment/components/FleetSegmentsWithTooltip/index.tsx
  frontend/src/features/FleetSegment/components/FleetSegmentsWithTooltip/utils.ts
  frontend/src/features/FleetSegment/components/VesselCurrentFleetSegmentDetails/index.tsx
  frontend/src/features/FleetSegment/components/VesselSidebarFleetSegments.tsx
  frontend/src/features/FleetSegment/constants.ts
  frontend/src/features/Logbook/components/VesselLogbook/LogbookSummary/index.tsx
  frontend/src/features/Logbook/components/VesselLogbook/index.tsx
  frontend/src/features/Map/components/TagInfo.tsx
  frontend/src/features/RiskFactor/components/details/ImpactRiskFactorDetails.tsx
  frontend/src/features/Vessel/components/VesselLabelOverlay/VesselLabel.tsx
  frontend/src/features/Vessel/components/VesselList/Row.tsx
  frontend/src/features/Vessel/components/VesselSidebar/components/Summary.tsx
  frontend/src/features/Vessel/components/VesselSidebar/components/common/common.style.tsx
  frontend/src/features/Vessel/layers/VesselsLabelsLayer/utils.ts
  frontend/src/features/Vessel/schemas/VesselSchema.ts
  frontend/src/features/Vessel/types/vessel.ts
Labels: feat. enhancement, data
